data_directory: data
access_log: access-{run_id}.yaml
fail_on_hash_mismatch: False
namespace: SCRC
read:
  - where:
      data_product: human/infection/SARS-CoV-2/asymptomatic-period
      component: asymptomatic-period
  - where:
      data_product: human/demographics/population/scotland
      component: grid1km/age/persons
