# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia: # https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/16
  - 1.4
  - 1.5
notifications:
  email: false

jobs:
  allow_failures:
    - julia: 1.5
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script: # https://github.com/JuliaLang/Pkg.jl/issues/492
        - julia --project=docs/ -e "using Pkg; Pkg.instantiate(); Pkg.build()"
        - julia --project=docs/ docs/make.jl
      after_success: skip

# install mpi
install:
  - source ci/travis/installMPI.sh

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project=@. -e "using Pkg; Pkg.activate(\".\"); Pkg.instantiate(); Pkg.build(\"Simulation\"); Pkg.test(\"Simulation\", coverage=true);"

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Simulation")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Simulation")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

before_cache:
  - rm -rf ~/.julia/packages/Simulation

cache:
  directories:
    - ~/openmpi
    - ~/openmpi-4.0.3
