name = "EcoSISTEM"
uuid = "ed2dc23b-ada4-5fdb-a26f-56368a14ad8f"
license = "LGPL-3.0-or-later"
authors = ["Claire Harris", "Richard Reeve <richard.reeve@glasgow.ac.uk>"]
version = "0.2.4"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Diversity = "d3d5718d-52de-57ab-b67a-eca7fd6175a4"
EcoBase = "a58aae7d-b440-5a11-b283-399458f99aac"
Feather = "becb17da-46f6-5d3c-ad1b-1c5fe96bc73c"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SpatialEcology = "348f2d5d-71a3-5ad4-b565-8af070f99681"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[weakdeps]
DataPipeline = "9ced6f0a-eb77-43a8-bbd1-bbf3031b0d12"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extensions]
EcoSISTEMDataPipelineExt = "DataPipeline"
EcoSISTEMERAExt = "PyCall"
EcoSISTEMMPIExt = "MPI"
EcoSISTEMPlotsExt = "Plots"

[compat]
ArchGDAL = "0.6, 0.7, 0.8, 0.9, 0.10"
AxisArrays = "0.4.3"
Calculus = "0.4.1, 0.5"
DataFrames = "0.21.8, 0.22, 1.0"
DataPipeline = "0.53"
Dates = "1.9"
Distributions = "0.24.15, 0.25"
Diversity = "0.5.6"
EcoBase = "0.1.3"
Feather = "0.5.7"
Git = "1"
HCubature = "1.5.0"
IndexedTables = "0.12.6, 0.13, 1"
Interpolations = "0.13.1, 0.14, 0.15"
JLD2 = "0.4.3"
JuliaFormatter = "1"
LibGit2 = "1.9"
Libdl = "1.9"
LinearAlgebra = "1.9"
Logging = "1.9"
MPI = "0.17.2, 0.18, 0.19, 0.20"
Markdown = "1.9"
Measures = "0.3.1"
Missings = "0.4.5, 1.0"
NetCDF = "0.10, 0.11, 0.12"
OnlineStats = "1.5.8"
Optim = "0.18, 0.19, 0.20, 0.21, 0.22, 1"
Phylo = "0.4.18, 0.5"
Pkg = "1.9"
Plots = "0.28.4, 0.29, 1"
Printf = "1.9"
PyCall = "1"
REPL = "1.9"
Random = "1.9"
RasterDataSources = "0.5.6, 0.6"
RecipesBase = "1"
ResearchSoftwareMetadata = "0.1.1"
SHA = "0.7"
SpatialEcology = "0.9"
Statistics = "1.9"
StatsBase = "0.32.2, 0.33, 0.34"
Test = "1.9"
UUIDs = "1.9"
Unitful = "1.7"
julia = "1.9"
p7zip_jll = "17"

[[author_details]]
name = "Claire Harris"
orcid = "0000-0003-0852-2340"
email = "Claire.Harris@defra.gov.uk"

    [[author_details.affiliation]]
    ror = "03jwrz939"
[[author_details]]
name = "Richard Reeve"
orcid = "0000-0003-2589-8091"
email = "richard.reeve@glasgow.ac.uk"

    [[author_details.affiliation]]
    ror = "00vtgdb53"

[extras]
DataPipeline = "9ced6f0a-eb77-43a8-bbd1-bbf3031b0d12"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ResearchSoftwareMetadata = "58378933-4625-47fa-851e-05ee27d397bd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataPipeline", "Git", "JuliaFormatter", "Logging", "MPI", "OnlineStats", "Pkg", "Plots", "ResearchSoftwareMetadata", "Test"]
