name = "EcoSISTEM"
uuid = "ed2dc23b-ada4-5fdb-a26f-56368a14ad8f"
authors = ["Claire Harris <claire.harris@bioss.ac.uk>", "Richard Reeve <Richard.Reeve@glasgow.ac.uk>"]
version = "0.1.2"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataPipeline = "9ced6f0a-eb77-43a8-bbd1-bbf3031b0d12"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Diversity = "d3d5718d-52de-57ab-b67a-eca7fd6175a4"
EcoBase = "a58aae7d-b440-5a11-b283-399458f99aac"
Feather = "becb17da-46f6-5d3c-ad1b-1c5fe96bc73c"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JLSO = "9da8a3cd-07a3-59c0-a743-3fdc52c30d11"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ArchGDAL = "0.6, 0.7"
AxisArrays = "0.4.3"
Calculus = "0.4.1, 0.5"
Conda = "1.5"
DataFrames = "0.21.8, 0.22, 1.0"
DataPipeline = "0.51"
Distributions = "0.24.15, 0.25"
Diversity = "0.5.6"
EcoBase = "0.1.3"
Feather = "0.5.7"
HCubature = "1.5"
HDF5 = "0.15"
HTTP = "0.8, 0.9"
IndexedTables = "0.12.6, 0.13, 1"
Interpolations = "0.13.1"
JLD2 = "0.4.3"
JLSO = "2.3"
MPI = "0.17.2, 0.18, 0.19"
Measures = "0.3.1"
Missings = "0.4.5, 1.0"
NetCDF = "0.11.3"
ORCA = "0.5"
OnlineStats = "1.5.8"
OnlineStatsBase = "1.4"
Phylo = "0.4.18"
Plots = "0.28.4, 0.29, 1"
RCall = "0.13.10"
RecipesBase = "0.7, 0.8, 1"
Requires = "1"
Revise = "3.1"
SQLite = "1.1"
StatsBase = "0.32.2, 0.33"
Unitful = "1.7"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HTTP", "MPI", "OnlineStats"]
