[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Diversity = "d3d5718d-52de-57ab-b67a-eca7fd6175a4"
EcoBase = "a58aae7d-b440-5a11-b283-399458f99aac"
EcoSISTEM = "ed2dc23b-ada4-5fdb-a26f-56368a14ad8f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
